#
# Module manifest for module 'Meadow-CLI'
#
# Generated by: Hosho Group
#
# Generated on: 8/20/2018
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = @(
                    ".\tools\netcoreapp2.1\any\Meadow.Cli.dll"
                  )
    
    # Version number of this module.
    ModuleVersion = '0.3.1.0'
    
    # SupportedPSEditions = @()
    
    CompatiblePSEditions = @("Core","Desk")
    
    # ID used to uniquely identify this module
    GUID = 'ec62eba8-b25e-4b28-98db-cb2a4def9a6b'
    
    # Author of this module
    Author = 'Hosho Group'
    
    # Company or vendor of this module
    CompanyName = 'Hosho Group'
    
    # Copyright statement for this module
    Copyright = '(c) Hosho Group. All rights reserved.'
    
    # Description of the functionality provided by this module
    Description = 'This module defines a set of basic Cmdlets to work with the Meadow test framework at a PowerShell prompt.'
    
    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '6.1'
    
    # Name of the PowerShell host required by this module
    PowerShellHostName = 'ConsoleHost'
    
    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''
    
    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    DotNetFrameworkVersion = '2.1.3'
    
    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''
    
    # Processor architecture (None, X86, Amd64) required by this module
    ProcessorArchitecture = 'Amd64'
    
    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()
    
    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()
#>
    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()
    
    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()
    
    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()
    
    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @()
    
    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @(
                            "Compile-Solidity",
                            "Generate-Accounts",
                            "Build-Solidity",
                            "Deploy-Contract",
                            "Initialize-Workspace",
                            "New-Accounts",
                            "Read-Accounts",
                            "Start-TestServer",
                            "Test-Function",
                            "Update-Config",
                            "Watch-Config",
                            "Watch-Solidity",
                            "Write-Accounts",
							"Get-Template",
							"Expand-Template"
                        )
    
    # Variables to export from this module
    VariablesToExport = '*'
    
    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @(
                            "Compile-Solidity",
                            "compileSol",
                            "config",
                            "deployContract",
                            "Generate-Accounts",
                            "generateAccounts",
                            "readAccounts",
                            "startTestServer",
                            "watchConfig",
                            "watchSol",
                            "writeAccounts"
                        )
    
    # DSC resources to export from this module
    DscResourcesToExport = @()
    
    # List of all modules packaged with this module
    ModuleList =  @(
                        '.\Meadow.Cli.psd1',
                        '.\tools\netcoreapp2.1\any\Meadow.Cli.dll'
                    )
                    
    
    # List of all files packaged with this module
    FileList = @(
                    ".\Help\about_Meadow.Cli.Help.txt",
                    ".\Help\Meadow.Cli-Help.md",
                    ".\Help\Meadow.Cli-Help.xml",
                    ".\tools\netcoreapp2.1\any\BouncyCastle.Crypto.dll",
                    ".\tools\netcoreapp2.1\any\DotnetToolSettings.xml",
                    ".\tools\netcoreapp2.1\any\Dynamitey.dll",
                    ".\tools\netcoreapp2.1\any\ExposedObject.dll",
                    ".\tools\netcoreapp2.1\any\ImpromptuInterface.dll",
                    ".\tools\netcoreapp2.1\any\Markdig.dll",
                    ".\tools\netcoreapp2.1\any\McMaster.Extensions.CommandLineUtils.dll",
                    ".\tools\netcoreapp2.1\any\Meadow.Cli.deps.json",
                    ".\tools\netcoreapp2.1\any\Meadow.Cli.dll",
                    ".\tools\netcoreapp2.1\any\Meadow.Cli.pdb",
                    ".\tools\netcoreapp2.1\any\Meadow.Cli.runtimeconfig.json",
                    ".\tools\netcoreapp2.1\any\Meadow.Cli.xml",
                    ".\tools\netcoreapp2.1\any\Meadow.Contract.dll",
                    ".\tools\netcoreapp2.1\any\Meadow.Contract.pdb",
                    ".\tools\netcoreapp2.1\any\Meadow.Contract.xml",
                    ".\tools\netcoreapp2.1\any\Meadow.Core.dll",
                    ".\tools\netcoreapp2.1\any\Meadow.Core.pdb",
                    ".\tools\netcoreapp2.1\any\Meadow.Core.xml",
                    ".\tools\netcoreapp2.1\any\Meadow.EVM.dll",
                    ".\tools\netcoreapp2.1\any\Meadow.EVM.pdb",
                    ".\tools\netcoreapp2.1\any\Meadow.EVM.xml",
                    ".\tools\netcoreapp2.1\any\Meadow.JsonRpc.Client.dll",
                    ".\tools\netcoreapp2.1\any\Meadow.JsonRpc.Client.pdb",
                    ".\tools\netcoreapp2.1\any\Meadow.JsonRpc.Client.xml",
                    ".\tools\netcoreapp2.1\any\Meadow.JsonRpc.dll",
                    ".\tools\netcoreapp2.1\any\Meadow.JsonRpc.pdb",
                    ".\tools\netcoreapp2.1\any\Meadow.JsonRpc.Server.dll",
                    ".\tools\netcoreapp2.1\any\Meadow.JsonRpc.Server.pdb",
                    ".\tools\netcoreapp2.1\any\Meadow.JsonRpc.Server.xml",
                    ".\tools\netcoreapp2.1\any\Meadow.JsonRpc.xml",
                    ".\tools\netcoreapp2.1\any\Meadow.SolCodeGen.dll",
                    ".\tools\netcoreapp2.1\any\Meadow.SolCodeGen.pdb",
                    ".\tools\netcoreapp2.1\any\Meadow.SolCodeGen.xml",
                    ".\tools\netcoreapp2.1\any\Meadow.TestNode.dll",
                    ".\tools\netcoreapp2.1\any\Meadow.TestNode.pdb",
                    ".\tools\netcoreapp2.1\any\Meadow.TestNode.xml",
                    ".\tools\netcoreapp2.1\any\Microsoft.ApplicationInsights.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.Connections.Abstractions.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.Cryptography.Internal.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.Cryptography.KeyDerivation.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.Hosting.Abstractions.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.Hosting.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.Hosting.Server.Abstractions.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.Http.Abstractions.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.Http.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.Http.Extensions.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.Http.Features.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.Server.Kestrel.Core.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.Server.Kestrel.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.Server.Kestrel.Https.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.AspNetCore.WebUtilities.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.CodeAnalysis.CSharp.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.CodeAnalysis.CSharp.Features.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.CodeAnalysis.CSharp.Workspaces.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.CodeAnalysis.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.CodeAnalysis.Features.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.CodeAnalysis.Workspaces.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.DotNet.PlatformAbstractions.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.Configuration.Abstractions.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.Configuration.Binder.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.Configuration.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.Configuration.EnvironmentVariables.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.Configuration.FileExtensions.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.DependencyInjection.Abstractions.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.DependencyInjection.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.DependencyModel.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.FileProviders.Abstractions.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.FileProviders.Physical.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.FileSystemGlobbing.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.Hosting.Abstractions.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.Http.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.Logging.Abstractions.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.Logging.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.ObjectPool.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.Options.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Extensions.Primitives.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Net.Http.Headers.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Win32.Registry.AccessControl.dll",
                    ".\tools\netcoreapp2.1\any\Microsoft.Win32.SystemEvents.dll",
                    ".\tools\netcoreapp2.1\any\Newtonsoft.Json.dll",
                    ".\tools\netcoreapp2.1\any\NJsonSchema.dll",
                    ".\tools\netcoreapp2.1\any\Secp256k1.Net.dll",
                    ".\tools\netcoreapp2.1\any\SolcNet.dll",
                    ".\tools\netcoreapp2.1\any\System.CodeDom.dll",
                    ".\tools\netcoreapp2.1\any\System.ComponentModel.Composition.dll",
                    ".\tools\netcoreapp2.1\any\System.Composition.AttributedModel.dll",
                    ".\tools\netcoreapp2.1\any\System.Composition.Convention.dll",
                    ".\tools\netcoreapp2.1\any\System.Composition.Hosting.dll",
                    ".\tools\netcoreapp2.1\any\System.Composition.Runtime.dll",
                    ".\tools\netcoreapp2.1\any\System.Composition.TypedParts.dll",
                    ".\tools\netcoreapp2.1\any\System.Configuration.ConfigurationManager.dll",
                    ".\tools\netcoreapp2.1\any\System.Data.DataSetExtensions.dll",
                    ".\tools\netcoreapp2.1\any\System.Data.Odbc.dll",
                    ".\tools\netcoreapp2.1\any\System.Data.SqlClient.dll",
                    ".\tools\netcoreapp2.1\any\System.Diagnostics.EventLog.dll",
                    ".\tools\netcoreapp2.1\any\System.Diagnostics.PerformanceCounter.dll",
                    ".\tools\netcoreapp2.1\any\System.DirectoryServices.AccountManagement.dll",
                    ".\tools\netcoreapp2.1\any\System.DirectoryServices.dll",
                    ".\tools\netcoreapp2.1\any\System.DirectoryServices.Protocols.dll",
                    ".\tools\netcoreapp2.1\any\System.Drawing.Common.dll",
                    ".\tools\netcoreapp2.1\any\System.IO.Packaging.dll",
                    ".\tools\netcoreapp2.1\any\System.IO.Pipelines.dll",
                    ".\tools\netcoreapp2.1\any\System.IO.Ports.dll",
                    ".\tools\netcoreapp2.1\any\System.Management.dll",
                    ".\tools\netcoreapp2.1\any\System.Net.Http.WinHttpHandler.dll",
                    ".\tools\netcoreapp2.1\any\System.Runtime.Caching.dll",
                    ".\tools\netcoreapp2.1\any\System.Runtime.CompilerServices.Unsafe.dll",
                    ".\tools\netcoreapp2.1\any\System.Security.Cryptography.Pkcs.dll",
                    ".\tools\netcoreapp2.1\any\System.Security.Cryptography.ProtectedData.dll",
                    ".\tools\netcoreapp2.1\any\System.Security.Cryptography.Xml.dll",
                    ".\tools\netcoreapp2.1\any\System.Security.Permissions.dll",
                    ".\tools\netcoreapp2.1\any\System.ServiceModel.dll",
                    ".\tools\netcoreapp2.1\any\System.ServiceModel.Duplex.dll",
                    ".\tools\netcoreapp2.1\any\System.ServiceModel.Http.dll",
                    ".\tools\netcoreapp2.1\any\System.ServiceModel.NetTcp.dll",
                    ".\tools\netcoreapp2.1\any\System.ServiceModel.Primitives.dll",
                    ".\tools\netcoreapp2.1\any\System.ServiceModel.Security.dll",
                    ".\tools\netcoreapp2.1\any\System.ServiceModel.Syndication.dll",
                    ".\tools\netcoreapp2.1\any\System.ServiceProcess.ServiceController.dll",
                    ".\tools\netcoreapp2.1\any\System.Text.Encoding.CodePages.dll",
                    ".\tools\netcoreapp2.1\any\System.Text.Encodings.Web.dll",
                    ".\tools\netcoreapp2.1\any\System.Threading.AccessControl.dll",
                    ".\tools\netcoreapp2.1\any\native\linux-x64\libsecp256k1.so",
                    ".\tools\netcoreapp2.1\any\native\linux-x64\libsolc.so",
                    ".\tools\netcoreapp2.1\any\native\osx-x64\libsecp256k1.dylib",
                    ".\tools\netcoreapp2.1\any\native\osx-x64\libsolc.dylib",
                    ".\tools\netcoreapp2.1\any\native\win-x64\secp256k1.dll",
                    ".\tools\netcoreapp2.1\any\native\win-x64\solc.dll",
                    ".\tools\netcoreapp2.1\any\native\win-x86\secp256k1.dll",
                    ".\tools\netcoreapp2.1\any\native\win-x86\solc.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux\lib\netcoreapp2.0\System.Data.Odbc.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-arm\lib\netstandard2.0\Microsoft.PowerShell.Commands.Management.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-arm\lib\netstandard2.0\Microsoft.PowerShell.Commands.Utility.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-arm\lib\netstandard2.0\Microsoft.PowerShell.ConsoleHost.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-arm\lib\netstandard2.0\Microsoft.PowerShell.CoreCLR.Eventing.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-arm\lib\netstandard2.0\Microsoft.PowerShell.MarkdownRender.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-arm\lib\netstandard2.0\Microsoft.PowerShell.SDK.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-arm\lib\netstandard2.0\Microsoft.PowerShell.Security.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-arm\lib\netstandard2.0\System.Management.Automation.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-arm\native\libpsl-native.so",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-x64\lib\netstandard2.0\Microsoft.PowerShell.Commands.Management.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-x64\lib\netstandard2.0\Microsoft.PowerShell.Commands.Utility.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-x64\lib\netstandard2.0\Microsoft.PowerShell.ConsoleHost.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-x64\lib\netstandard2.0\Microsoft.PowerShell.CoreCLR.Eventing.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-x64\lib\netstandard2.0\Microsoft.PowerShell.MarkdownRender.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-x64\lib\netstandard2.0\Microsoft.PowerShell.SDK.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-x64\lib\netstandard2.0\Microsoft.PowerShell.Security.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-x64\lib\netstandard2.0\System.Management.Automation.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-x64\native\libmi.so",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-x64\native\libpsl-native.so",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-x64\native\libpsrpclient.so",
                    ".\tools\netcoreapp2.1\any\runtimes\linux-x64\native\libsecp256k1.so",
                    ".\tools\netcoreapp2.1\any\runtimes\osx\lib\netcoreapp2.0\System.Data.Odbc.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\osx\lib\netstandard2.0\Microsoft.PowerShell.Commands.Management.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\osx\lib\netstandard2.0\Microsoft.PowerShell.Commands.Utility.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\osx\lib\netstandard2.0\Microsoft.PowerShell.ConsoleHost.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\osx\lib\netstandard2.0\Microsoft.PowerShell.CoreCLR.Eventing.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\osx\lib\netstandard2.0\Microsoft.PowerShell.MarkdownRender.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\osx\lib\netstandard2.0\Microsoft.PowerShell.SDK.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\osx\lib\netstandard2.0\Microsoft.PowerShell.Security.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\osx\lib\netstandard2.0\System.Management.Automation.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\osx\native\libmi.dylib",
                    ".\tools\netcoreapp2.1\any\runtimes\osx\native\libpsl-native.dylib",
                    ".\tools\netcoreapp2.1\any\runtimes\osx\native\libpsrpclient.dylib",
                    ".\tools\netcoreapp2.1\any\runtimes\osx-x64\native\libsecp256k1.dylib",
                    ".\tools\netcoreapp2.1\any\runtimes\unix\lib\netcoreapp2.0\System.Drawing.Common.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\unix\lib\netcoreapp2.0\System.Runtime.Caching.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\unix\lib\netcoreapp2.1\System.Data.SqlClient.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\unix\lib\netstandard1.6\Microsoft.Management.Infrastructure.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\unix\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\unix\lib\netstandard2.0\System.Private.ServiceModel.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netcoreapp2.0\Microsoft.Win32.SystemEvents.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netcoreapp2.0\System.Data.Odbc.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netcoreapp2.0\System.Diagnostics.EventLog.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netcoreapp2.0\System.Diagnostics.PerformanceCounter.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netcoreapp2.0\System.DirectoryServices.AccountManagement.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netcoreapp2.0\System.DirectoryServices.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netcoreapp2.0\System.DirectoryServices.Protocols.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netcoreapp2.0\System.Drawing.Common.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netcoreapp2.0\System.Management.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netcoreapp2.0\System.Runtime.Caching.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netcoreapp2.0\System.Text.Encoding.CodePages.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netcoreapp2.1\System.Data.SqlClient.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netcoreapp2.1\System.Security.Cryptography.Pkcs.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netstandard2.0\Microsoft.Win32.Registry.AccessControl.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netstandard2.0\System.IO.Ports.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netstandard2.0\System.Net.Http.WinHttpHandler.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netstandard2.0\System.Private.ServiceModel.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netstandard2.0\System.Security.Cryptography.ProtectedData.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netstandard2.0\System.ServiceProcess.ServiceController.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win\lib\netstandard2.0\System.Threading.AccessControl.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\lib\netstandard1.6\Microsoft.Management.Infrastructure.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\lib\netstandard2.0\Microsoft.PowerShell.Commands.Diagnostics.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\lib\netstandard2.0\Microsoft.PowerShell.Commands.Management.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\lib\netstandard2.0\Microsoft.PowerShell.Commands.Utility.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\lib\netstandard2.0\Microsoft.PowerShell.ConsoleHost.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\lib\netstandard2.0\Microsoft.PowerShell.CoreCLR.Eventing.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\lib\netstandard2.0\Microsoft.PowerShell.MarkdownRender.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\lib\netstandard2.0\Microsoft.PowerShell.SDK.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\lib\netstandard2.0\Microsoft.PowerShell.Security.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\lib\netstandard2.0\Microsoft.WSMan.Management.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\lib\netstandard2.0\Microsoft.WSMan.Runtime.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\lib\netstandard2.0\System.Management.Automation.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\native\mi.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\native\Microsoft.Management.Infrastructure.Native.Unmanaged.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\native\miutils.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\native\PowerShell.Core.Instrumentation.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\native\pwrshplugin.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm\native\pwrshplugin.pdb",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\lib\netstandard1.6\Microsoft.Management.Infrastructure.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\lib\netstandard2.0\Microsoft.PowerShell.Commands.Diagnostics.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\lib\netstandard2.0\Microsoft.PowerShell.Commands.Management.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\lib\netstandard2.0\Microsoft.PowerShell.Commands.Utility.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\lib\netstandard2.0\Microsoft.PowerShell.ConsoleHost.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\lib\netstandard2.0\Microsoft.PowerShell.CoreCLR.Eventing.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\lib\netstandard2.0\Microsoft.PowerShell.MarkdownRender.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\lib\netstandard2.0\Microsoft.PowerShell.SDK.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\lib\netstandard2.0\Microsoft.PowerShell.Security.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\lib\netstandard2.0\Microsoft.WSMan.Management.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\lib\netstandard2.0\Microsoft.WSMan.Runtime.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\lib\netstandard2.0\System.Management.Automation.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\native\mi.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\native\Microsoft.Management.Infrastructure.Native.Unmanaged.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\native\miutils.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\native\PowerShell.Core.Instrumentation.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\native\pwrshplugin.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\native\pwrshplugin.pdb",
                    ".\tools\netcoreapp2.1\any\runtimes\win-arm64\native\sni.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\lib\netstandard2.0\Microsoft.PowerShell.Commands.Diagnostics.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\lib\netstandard2.0\Microsoft.PowerShell.Commands.Management.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\lib\netstandard2.0\Microsoft.PowerShell.Commands.Utility.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\lib\netstandard2.0\Microsoft.PowerShell.ConsoleHost.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\lib\netstandard2.0\Microsoft.PowerShell.CoreCLR.Eventing.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\lib\netstandard2.0\Microsoft.PowerShell.MarkdownRender.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\lib\netstandard2.0\Microsoft.PowerShell.SDK.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\lib\netstandard2.0\Microsoft.PowerShell.Security.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\lib\netstandard2.0\Microsoft.WSMan.Management.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\lib\netstandard2.0\Microsoft.WSMan.Runtime.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\lib\netstandard2.0\System.Management.Automation.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\native\PowerShell.Core.Instrumentation.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\native\pwrshplugin.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\native\pwrshplugin.pdb",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\native\secp256k1.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x64\native\sni.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\lib\netstandard2.0\Microsoft.PowerShell.Commands.Diagnostics.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\lib\netstandard2.0\Microsoft.PowerShell.Commands.Management.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\lib\netstandard2.0\Microsoft.PowerShell.Commands.Utility.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\lib\netstandard2.0\Microsoft.PowerShell.ConsoleHost.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\lib\netstandard2.0\Microsoft.PowerShell.CoreCLR.Eventing.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\lib\netstandard2.0\Microsoft.PowerShell.MarkdownRender.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\lib\netstandard2.0\Microsoft.PowerShell.SDK.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\lib\netstandard2.0\Microsoft.PowerShell.Security.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\lib\netstandard2.0\Microsoft.WSMan.Management.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\lib\netstandard2.0\Microsoft.WSMan.Runtime.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\lib\netstandard2.0\System.Management.Automation.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\native\PowerShell.Core.Instrumentation.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\native\pwrshplugin.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\native\pwrshplugin.pdb",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\native\secp256k1.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win-x86\native\sni.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win10-x64\lib\netstandard1.6\Microsoft.Management.Infrastructure.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win10-x64\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win10-x64\native\mi.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win10-x64\native\Microsoft.Management.Infrastructure.Native.Unmanaged.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win10-x64\native\miutils.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win10-x86\lib\netstandard1.6\Microsoft.Management.Infrastructure.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win10-x86\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win10-x86\native\mi.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win10-x86\native\Microsoft.Management.Infrastructure.Native.Unmanaged.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win10-x86\native\miutils.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win7-x64\lib\netstandard1.6\Microsoft.Management.Infrastructure.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win7-x64\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win7-x64\native\mi.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win7-x64\native\Microsoft.Management.Infrastructure.Native.Unmanaged.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win7-x64\native\miutils.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win7-x86\lib\netstandard1.6\Microsoft.Management.Infrastructure.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win7-x86\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win7-x86\native\mi.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win7-x86\native\Microsoft.Management.Infrastructure.Native.Unmanaged.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win7-x86\native\miutils.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win8-x64\lib\netstandard1.6\Microsoft.Management.Infrastructure.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win8-x64\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win8-x64\native\mi.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win8-x64\native\Microsoft.Management.Infrastructure.Native.Unmanaged.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win8-x64\native\miutils.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win8-x86\lib\netstandard1.6\Microsoft.Management.Infrastructure.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win8-x86\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win8-x86\native\mi.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win8-x86\native\Microsoft.Management.Infrastructure.Native.Unmanaged.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win8-x86\native\miutils.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win81-x64\lib\netstandard1.6\Microsoft.Management.Infrastructure.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win81-x64\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win81-x64\native\mi.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win81-x64\native\Microsoft.Management.Infrastructure.Native.Unmanaged.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win81-x64\native\miutils.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win81-x86\lib\netstandard1.6\Microsoft.Management.Infrastructure.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win81-x86\lib\netstandard1.6\Microsoft.Management.Infrastructure.Native.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win81-x86\native\mi.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win81-x86\native\Microsoft.Management.Infrastructure.Native.Unmanaged.dll",
                    ".\tools\netcoreapp2.1\any\runtimes\win81-x86\native\miutils.dll"
                )
    
    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
    
        PSData = @{
    
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = 'Meadow', 'CLI', 'Meadow.Cli', 'Etherium', 'Eth', 'Test', 'Framework'
    
            # A URL to the license for this module.
            LicenseUri = 'https://gitlab.hoshogroup.com/company-projects/Meadow'
    
            # A URL to the main website for this project.
            ProjectUri = 'https://gitlab.hoshogroup.com/company-projects/Meadow'
    
            # A URL to an icon representing this module.
            # IconUri = ''
    
            # ReleaseNotes of this module
            ReleaseNotes = 'https://gitlab.hoshogroup.com/company-projects/Meadow'
    
        } # End of PSData hashtable
    
    } # End of PrivateData hashtable
    
    # HelpInfo URI of this module
    HelpInfoURI = 'https://gitlab.hoshogroup.com/company-projects/Meadow'
    
    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
    
    }
    
    